# Generated by Django 6.0.2 on 2026-02-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('turma', models.CharField(max_length=50)),
                ('equipamento', models.CharField(choices=[('notebook', 'Notebook'), ('tablet', 'Tablet')], default='notebook', max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('software_especifico', models.TextField(blank=True, verbose_name='Precisa de algum software?')),
                ('quantidade_aulas', models.PositiveIntegerField(verbose_name='Por quantas aulas usará?')),
                ('perifericos', models.TextField(blank=True, verbose_name='Precisa de algum periférico?')),
                ('data_inicio', models.DateTimeField(null=True, verbose_name='Início do Agendamento')),
                ('data_fim', models.DateTimeField(null=True, verbose_name='Fim do Agendamento')),
                ('entregue', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Aguardando Aprovação'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_notebooks', models.IntegerField(default=13, verbose_name='Limite de Notebooks')),
                ('limite_tablets', models.IntegerField(default=20, verbose_name='Limite de Tablets')),
                ('texto_instrucoes', models.TextField(default='Preencha as informações abaixo.', verbose_name='instruções do Form')),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
    ]
