# Generated by Django 6.0.2 on 2026-03-02 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='quantidade_aulas',
        ),
    ]
