# Generated by Django 6.0.2 on 2026-03-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_remove_agendamento_quantidade_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracao',
            name='limite_notebooks',
            field=models.IntegerField(default=26, verbose_name='Limite de Notebooks'),
        ),
    ]
