# Generated by Django 6.0.2 on 2026-03-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_alter_configuracao_limite_notebooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='aceitou_termos',
            field=models.BooleanField(default=False, verbose_name='Aceitou os Termos'),
        ),
    ]
