# Generated by Django 6.0.2 on 2026-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_agendamento_aceitou_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='limite_aprovacao_automatica',
            field=models.IntegerField(default=13, verbose_name='Limite de Aprovação Automática (Notebooks)'),
        ),
    ]
