# Generated by Django 6.0.2 on 2026-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_configuracao_limite_aprovacao_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='antecedencia_minima',
            field=models.IntegerField(default=30, verbose_name='Antecedência Mínima para Agendamento (minutos)'),
        ),
    ]
