# Generated by Django 6.0.2 on 2026-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_configuracao_antecedencia_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracao',
            name='prazo_expiracao_pendente',
            field=models.IntegerField(default=5, verbose_name='Prazo para Expiração de Pendentes (dias)'),
        ),
    ]
