# Generated by Django 6.0.2 on 2026-03-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_configuracao_prazo_expiracao_pendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBloqueado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo (interno)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Bloqueado em')),
            ],
            options={
                'verbose_name': 'E-mail Bloqueado',
                'verbose_name_plural': 'E-mails Bloqueados',
            },
        ),
    ]
