# Generated by Django 6.0.3 on 2026-03-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_emailbloqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agendamento_criado', 'Agendamento Criado'), ('agendamento_aprovado', 'Agendamento Aprovado'), ('agendamento_rejeitado', 'Agendamento Rejeitado'), ('agendamento_expirado', 'Agendamento Expirado'), ('email_bloqueado', 'E-mail Bloqueado'), ('email_desbloqueado', 'E-mail Desbloqueado'), ('admin_criado', 'Admin Criado')], max_length=30, verbose_name='Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario', models.CharField(blank=True, max_length=150, verbose_name='Usuário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'ordering': ['-criado_em'],
            },
        ),
    ]
