# Generated by Django 6.0.3 on 2026-03-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_logatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='lembrete_enviado',
            field=models.BooleanField(default=False, verbose_name='Lembrete Enviado'),
        ),
    ]
